{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-9740", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:49 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-09-18", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/107466", "Description": "BID:107466"}, {"URL": "https://security.netapp.com/advisory/ntap-20190619-0005/", "Description": "CONFIRM:https://security.netapp.com/advisory/ntap-20190619-0005/"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/", "Description": "FEDORA:FEDORA-2019-1ffd6b6064"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/", "Description": "FEDORA:FEDORA-2019-7723d4774a"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/", "Description": "FEDORA:FEDORA-2019-7df59302e0"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/", "Description": "FEDORA:FEDORA-2019-ec26883852"}, {"URL": "https://bugs.python.org/issue36276", "Description": "MISC:https://bugs.python.org/issue36276"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html", "Description": "MLIST:[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html", "Description": "MLIST:[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-1] python3.4 security update"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html", "Description": "MLIST:[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-2] python3.4 regression update"}, {"URL": "https://access.redhat.com/errata/RHSA-2019:1260", "Description": "REDHAT:RHSA-2019:1260"}, {"URL": "https://access.redhat.com/errata/RHSA-2019:2030", "Description": "REDHAT:RHSA-2019:2030"}, {"URL": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html", "Description": "SUSE:openSUSE-SU-2019:2131"}, {"URL": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html", "Description": "SUSE:openSUSE-SU-2019:2133"}, {"URL": "https://usn.ubuntu.com/4127-1/", "Description": "UBUNTU:USN-4127-1"}, {"URL": "https://usn.ubuntu.com/4127-2/", "Description": "UBUNTU:USN-4127-2"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-03-12"}