{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-10904", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and roundup/cgi/wsgi_handler.py mishandle 404 errors.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:05 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-04-07", "cve_detail": "", "references": [{"URL": "https://bugs.python.org/issue36391", "Description": "MISC:https://bugs.python.org/issue36391"}, {"URL": "https://github.com/python/bugs.python.org/issues/34", "Description": "MISC:https://github.com/python/bugs.python.org/issues/34"}, {"URL": "https://www.openwall.com/lists/oss-security/2019/04/05/1", "Description": "MISC:https://www.openwall.com/lists/oss-security/2019/04/05/1"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/04/msg00009.html", "Description": "MLIST:[debian-lts-announce] 20190407 [SECURITY] [DLA 1750-1] roundup security update"}, {"URL": "http://www.openwall.com/lists/oss-security/2019/04/07/1", "Description": "MLIST:[oss-security] 20190407 Re: XSS in roundup bug tracker 404 page"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-04-06"}