{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-12902", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "Pydio Cells before 1.5.0 does incomplete cleanup of a user's data upon deletion. This allows a new user, holding the same User ID as a deleted user, to restore the deleted user's data.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:11 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-06-19", "cve_detail": "", "references": [{"URL": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security", "Description": "MISC:https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security"}, {"URL": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/", "Description": "MISC:https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-06-19"}