{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-4101", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 10.1, 10.5, and 11.1 is vulnerable to a denial of service. Users that have both EXECUTE on PD_GET_DIAG_HIST and access to the diagnostic directory on the DB2 server can cause the instance to crash. IBM X-Force ID: 158091.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:32 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-07-04", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/109021", "Description": "BID:109021"}, {"URL": "https://www.ibm.com/support/docview.wss?uid=ibm10880741", "Description": "CONFIRM:https://www.ibm.com/support/docview.wss?uid=ibm10880741"}, {"URL": "https://exchange.xforce.ibmcloud.com/vulnerabilities/158091", "Description": "XF:ibm-db2-cve20194101-dos (158091)"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-07-01"}