{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-6446", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "** DISPUTED ** \n\nAn issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:39 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-10-06", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/106670", "Description": "BID:106670"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/", "Description": "FEDORA:FEDORA-2019-1dfe95a864"}, {"URL": "https://bugzilla.suse.com/show_bug.cgi?id=1122208", "Description": "MISC:https://bugzilla.suse.com/show_bug.cgi?id=1122208"}, {"URL": "https://github.com/numpy/numpy/issues/12759", "Description": "MISC:https://github.com/numpy/numpy/issues/12759"}, {"URL": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html", "Description": "SUSE:openSUSE-SU-2019:2225"}, {"URL": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html", "Description": "SUSE:openSUSE-SU-2019:2227"}, {"URL": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html", "Description": "SUSE:openSUSE-SU-2019:2259"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-01-16"}