{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-16056", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:20 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-10-10", "cve_detail": "", "references": [{"URL": "https://security.netapp.com/advisory/ntap-20190926-0005/", "Description": "CONFIRM:https://security.netapp.com/advisory/ntap-20190926-0005/"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/", "Description": "FEDORA:FEDORA-2019-2b1f72899a"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K4KZEFP6E4YPYB52AF4WXCUDSGQOTF37/", "Description": "FEDORA:FEDORA-2019-4954d8773c"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NF3DRDGMVIRYNZMSLJIHNW47HOUQYXVG/", "Description": "FEDORA:FEDORA-2019-50772cf122"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/", "Description": "FEDORA:FEDORA-2019-5dc275c9f2"}, {"URL": "https://bugs.python.org/issue34155", "Description": "MISC:https://bugs.python.org/issue34155"}, {"URL": "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9", "Description": "MISC:https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/09/msg00018.html", "Description": "MLIST:[debian-lts-announce] 20190916 [SECURITY] [DLA 1924-1] python3.4 security update"}, {"URL": "https://lists.debian.org/debian-lts-announce/2019/09/msg00019.html", "Description": "MLIST:[debian-lts-announce] 20190916 [SECURITY] [DLA 1925-1] python2.7 security update"}, {"URL": "https://usn.ubuntu.com/4151-1/", "Description": "UBUNTU:USN-4151-1"}, {"URL": "https://usn.ubuntu.com/4151-2/", "Description": "UBUNTU:USN-4151-2"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-09-06"}