{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2019-1010142", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..). The attack vector is: over the network or in a pcap. both work.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:04:02 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-10-05", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/106674", "Description": "BID:106674"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T46XW4S5BCA3VV3JT3C5Q6LBEXSIACLN/", "Description": "FEDORA:FEDORA-2019-47946eb312"}, {"URL": "https://github.com/secdev/scapy/pull/1409", "Description": "MISC:https://github.com/secdev/scapy/pull/1409"}, {"URL": "https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058", "Description": "MISC:https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058"}, {"URL": "https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/", "Description": "MISC:https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/"}], "cve_repaire": "", "editor": "warcup", "add_time": "2019-07-19"}