{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-7886", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in CloudMe 1.11.0. An unauthenticated local attacker that can connect to the \"CloudMe Sync\" client application listening on 127.0.0.1 port 8888 can send a malicious payload causing a buffer overflow condition. This will result in code execution, as demonstrated by a TCP reverse shell, or a crash. NOTE: this vulnerability exists because of an incomplete fix for CVE-2018-6892.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:44:17 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-04-18", "cve_detail": "", "references": [{"URL": "https://www.exploit-db.com/exploits/44470/", "Description": "EXPLOIT-DB:44470"}, {"URL": "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/", "Description": "MISC:https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-03-14"}