{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-16855", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue has been found in PowerDNS Recursor before version 4.1.8 where a remote attacker sending a DNS query can trigger an out-of-bounds memory read while computing the hash of the query for a packet cache lookup, possibly leading to a crash.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:43:36 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-12-03", "cve_detail": "", "references": [{"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16855", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16855"}, {"URL": "https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2018-09.html", "Description": "MISC:https://docs.powerdns.com/recursor/security-advisories/powerdns-advisory-2018-09.html"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-12-03"}