{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2018-6892", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in CloudMe before 1.11.0. An unauthenticated remote attacker that can connect to the \"CloudMe Sync\" client application listening on port 8888 can send a malicious payload causing a buffer overflow condition. This will result in an attacker controlling the program's execution flow and allowing arbitrary code execution.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 14:44:13 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-01-29", "cve_detail": "", "references": [{"URL": "https://www.exploit-db.com/exploits/44027/", "Description": "EXPLOIT-DB:44027"}, {"URL": "https://www.exploit-db.com/exploits/44175/", "Description": "EXPLOIT-DB:44175"}, {"URL": "https://www.exploit-db.com/exploits/45197/", "Description": "EXPLOIT-DB:45197"}, {"URL": "https://www.exploit-db.com/exploits/46250/", "Description": "EXPLOIT-DB:46250"}, {"URL": "http://hyp3rlinx.altervista.org/advisories/CLOUDME-SYNC-UNAUTHENTICATED-REMOTE-BUFFER-OVERFLOW.txt", "Description": "MISC:http://hyp3rlinx.altervista.org/advisories/CLOUDME-SYNC-UNAUTHENTICATED-REMOTE-BUFFER-OVERFLOW.txt"}, {"URL": "https://blogs.securiteam.com/index.php/archives/3669", "Description": "MISC:https://blogs.securiteam.com/index.php/archives/3669"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-02-11"}