{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2015-3220", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "The tlslite library before 0.4.9 for Python allows remote attackers to trigger a denial of service (runtime exception and process crash).", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:02:45 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2017-06-13", "cve_detail": "", "references": [{"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1254215", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=1254215"}, {"URL": "https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853", "Description": "CONFIRM:https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853"}, {"URL": "https://groups.google.com/forum/#%21topic/tlslite-dev/MoWE7B0A4iU", "Description": "MLIST:[tslite-dev] 20150812 tlslite-0.4.9"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-06-13"}