{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2017-6301", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in ytnef before 1.9.1. This is related to a patch described as \"4 of 9. Out of Bounds Reads.\"", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 15:53:07 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2019-05-17", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/96423", "Description": "BID:96423"}, {"URL": "http://www.debian.org/security/2017/dsa-3846", "Description": "DEBIAN:DSA-3846"}, {"URL": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LFJWMUEUC4ILH2HEOCYVVLQT654ZMCGQ/", "Description": "FEDORA:FEDORA-2019-7d7083b8be"}, {"URL": "http://www.openwall.com/lists/oss-security/2017/02/15/4", "Description": "MISC:http://www.openwall.com/lists/oss-security/2017/02/15/4"}, {"URL": "https://github.com/Yeraze/ytnef/pull/27", "Description": "MISC:https://github.com/Yeraze/ytnef/pull/27"}, {"URL": "https://www.x41-dsec.de/lab/advisories/x41-2017-002-ytnef/", "Description": "MISC:https://www.x41-dsec.de/lab/advisories/x41-2017-002-ytnef/"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-02-23"}