{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2017-18207", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "** DISPUTED ** The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \"need to be prepared to handle a wide variety of exceptions.\"", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 15:52:57 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-03-02", "cve_detail": "", "references": [{"URL": "https://bugs.python.org/issue32056", "Description": "MISC:https://bugs.python.org/issue32056"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-03-01"}