{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2017-2592", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulnerable to an information disclosure. Software using the CatchError class could include sensitive values in a traceback's error message. System users could exploit this flaw to obtain sensitive information from OpenStack component error logs (for example, keystone tokens).", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 15:52:59 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-06-01", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/95827", "Description": "BID:95827"}, {"URL": "http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html", "Description": "CONFIRM:http://lists.openstack.org/pipermail/openstack-announce/2017-January/002002.html"}, {"URL": "https://access.redhat.com/errata/RHSA-2017:0300", "Description": "CONFIRM:https://access.redhat.com/errata/RHSA-2017:0300"}, {"URL": "https://access.redhat.com/errata/RHSA-2017:0435", "Description": "CONFIRM:https://access.redhat.com/errata/RHSA-2017:0435"}, {"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-2592"}, {"URL": "https://bugs.launchpad.net/keystonemiddleware/+bug/1628031", "Description": "MISC:https://bugs.launchpad.net/keystonemiddleware/+bug/1628031"}, {"URL": "https://review.openstack.org/#/c/425730/", "Description": "MISC:https://review.openstack.org/#/c/425730/"}, {"URL": "https://review.openstack.org/#/c/425732/", "Description": "MISC:https://review.openstack.org/#/c/425732/"}, {"URL": "https://review.openstack.org/#/c/425734/", "Description": "MISC:https://review.openstack.org/#/c/425734/"}, {"URL": "http://rhn.redhat.com/errata/RHSA-2017-0300.html", "Description": "REDHAT:RHSA-2017:0300"}, {"URL": "http://rhn.redhat.com/errata/RHSA-2017-0435.html", "Description": "REDHAT:RHSA-2017:0435"}, {"URL": "https://usn.ubuntu.com/3666-1/", "Description": "UBUNTU:USN-3666-1"}], "cve_repaire": "", "editor": "warcup", "add_time": "2018-05-08"}