{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2017-10708", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An issue was discovered in Apport through 2.20.x. In apport/report.py, Apport sets the ExecutablePath field and it then uses the path to run package specific hooks without protecting against path traversal. This allows remote attackers to execute arbitrary code via a crafted .crash file.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 15:52:43 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2017-07-18", "cve_detail": "", "references": [{"URL": "https://launchpad.net/bugs/1700573", "Description": "CONFIRM:https://launchpad.net/bugs/1700573"}, {"URL": "https://launchpad.net/ubuntu/+source/apport/+changelog", "Description": "CONFIRM:https://launchpad.net/ubuntu/+source/apport/+changelog"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-07-18"}