{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2017-5601", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 15:53:06 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2018-11-30", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/95837", "Description": "BID:95837"}, {"URL": "https://github.com/libarchive/libarchive/commit/98dcbbf0bf4854bf987557e55e55fff7abbf3ea9", "Description": "MISC:https://github.com/libarchive/libarchive/commit/98dcbbf0bf4854bf987557e55e55fff7abbf3ea9"}, {"URL": "https://secunia.com/secunia_research/2017-3/", "Description": "MISC:https://secunia.com/secunia_research/2017-3/"}, {"URL": "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html", "Description": "MLIST:[debian-lts-announce] 20181129 [SECURITY] [DLA 1600-1] libarchive security update"}, {"URL": "http://www.securitytracker.com/id/1037974", "Description": "SECTRACK:1037974"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-01-27"}