{"cve_repaire_en": "", "cve_code_exp_url": "", "cve_id": "CVE-2016-4445", "cve_categories": ["category1", "category2"], "cve_code_detect_url": "", "cve_name": "cve_name", "cve_risk_level": "determine", "cve_detail_en": "The fix_lookup_id function in sealert in setroubleshoot before 3.2.23 allows local users to execute arbitrary commands as root by triggering an SELinux denial with a crafted file name, related to executing external commands with the commands.getstatusoutput function.", "cve_name_en": "cve_name_en", "edit_time": "Sat Oct 12 16:01:40 2019", "cve_code_des_url": "", "cve_other_info": "", "modify_time": "2017-04-12", "cve_detail": "", "references": [{"URL": "http://www.securityfocus.com/bid/91430", "Description": "BID:91430"}, {"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1339183", "Description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=1339183"}, {"URL": "https://github.com/fedora-selinux/setroubleshoot/commit/2d12677629ca319310f6263688bb1b7f676c01b7", "Description": "CONFIRM:https://github.com/fedora-selinux/setroubleshoot/commit/2d12677629ca319310f6263688bb1b7f676c01b7"}, {"URL": "http://seclists.org/oss-sec/2016/q2/575", "Description": "MLIST:[oss-security] 20160621 Re: SELinux troubles"}, {"URL": "https://rhn.redhat.com/errata/RHSA-2016-1267.html", "Description": "REDHAT:RHSA-2016:1267"}, {"URL": "http://www.securitytracker.com/id/1036144", "Description": "SECTRACK:1036144"}], "cve_repaire": "", "editor": "warcup", "add_time": "2017-04-11"}